#ifndef __org_libreoffice_example_xcass_idl__
#define __org_libreoffice_example_xcass_idl__


module cass { module libreOffice {
	struct WSD_Result{
		unsigned long SynonymCount;
		unsigned long SynsetSize;
		sequence< sequence<string> > Synonyms;
	};
};};


module org { module libreoffice { module example { 	
	
	interface XCASS {
		[attribute] long synonymCount;
		[attribute] long synsetCount;
		[attribute] sequence <sequence <string> > synonyms;
		void getSynonym([in] string leftContext, [in] string target, [in] string rightContext, [in] string language, [in] string algorithm);
	};

	

 }; }; };
#endif
